### ISSUE TITLE
Tickets page 4 days instead of 5 days and clarification for the total days

### ISSUE THREAD

**Issue by HypiTheFox** [Fluufff/Website-issues#11]
On the tickets page, there is '4 days' but it's 5 days.
Also, someone told me we should add the days in small below the total of days:
5 days
(wednessday to sunday)
Early
(tuesday)
Late
(monday)

**Comment by gabrielTach** [comment]
Fixed the 4 days to 5 days in Fluufff/Website@a0f36d16ef8acd2b954034f60872aea53f45d6f8
Assigning @HybridFox for the small text.
