### ISSUE TITLE
Legal texts not up-to-date

### ISSUE THREAD

**Issue by HypiTheFox** [Fluufff/Website-issues#13]
Stan made an edited version in the google drive texts files for website.
If you click on the cookiebanner link, the rules are lacking ^.^

**Comment by gabrielTach** [comment]
Texts updated in Fluufff/Website-issues@39c0be0e47187c8275f45d87555d8259cf4ee55f

Might need some better styling.

**Comment by HypiTheFox** [comment]
Styling done!
