### ISSUE TITLE
Exectutive bedroom for 2 out of stock

### ISSUE THREAD

**Issue by Akylos5885** [Fluufff/Website-issues#16]
Exectutive bedroom for 2 can be chosen (both entire room or just a spot), but can't be added tot he cart because is out of stock afterwards.

**Comment by Akylos5885** [comment]
![image](https://user-images.githubusercontent.com/62029503/76340238-8b345f00-62fb-11ea-837e-9a65fc99f477.png)
![image](https://user-images.githubusercontent.com/62029503/76340257-912a4000-62fb-11ea-8ffa-13052e93ff9d.png)

**Comment by gabrielTach** [comment]
Fixed in Fluufff/Website@ed0c1b806aed9dc48300f49805cd62e0fdf31f88
