### ISSUE TITLE
Finishing payment through stripe shows PHP error in Booking  information

### ISSUE THREAD

**Issue by Akylos5885** [Fluufff/Website-issues#18]
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: booking_freeze

Filename: register/book.php

Line Number: 12

Backtrace:

File: /home/www/fluufff-test/platyplus/views/register/book.php
Line: 12
Function: _error_handler

File: /home/www/fluufff-test/platyplus/third_party/MX/Loader.php
Line: 363
Function: include

File: /home/www/fluufff-test/platyplus/third_party/MX/Loader.php
Line: 305
Function: _ci_load

File: /home/www/fluufff-test/platyplus/controllers/Register.php
Line: 1207
Function: view

File: /home/www/fluufff-test/platyplus/controllers/Register.php
Line: 791
Function: register_view

File: /home/www/fluufff-test/platyplus/controllers/Register.php
Line: 577
Function: booking

File: /home/www/fluufff-test/index.php
Line: 315
Function: require_once

![image](https://user-images.githubusercontent.com/62029503/76341217-04808180-62fd-11ea-8778-c06bf6bd6b5a.png)

**Comment by gabrielTach** [comment]
Solved in Fluufff/Website@a6717a69dc467e3aebf19b2e0fa526c8967b089d
