### ISSUE TITLE
Schedule event timeline

### ISSUE THREAD

**Issue by gabrielTach** [Fluufff/Website-issues#2]
Left red time line dissapears when the name of the event is too big relatively to the size of the column in Firefox 73.0 (not tested on other browser).
![image](https://user-images.githubusercontent.com/6368290/75634709-53992900-5c10-11ea-946e-a161e42b7f98.png)
Originally
![image](https://user-images.githubusercontent.com/6368290/75634706-48de9400-5c10-11ea-80f2-6f0b6974af21.png)
When the name is trimmed

**Comment by HybridFox** [comment]
removed the max-height on the card and implemented a fix for above issue in https://github.com/Fluufff/Website/commit/bbee00b5e186f95801328b81e01908bb2d0c9220
