### ISSUE TITLE
Replace placeholder logo's

### ISSUE THREAD

**Issue by inekdebo** [Fluufff/Website-issues#22]
Replace logo's on:

-Homepage (there's still a plain red version as placeholder)
-Full logo left of navigation bar
-Flavicon 

All versions can be found here: https://drive.google.com/drive/folders/1wLrC4i8JoF91cPjnhXedgXTuRjgCB1hf
(for favicon unzip the file 'favicon' and see .txt file for source code)

**Comment by inekdebo** [comment]
If possible also replace video of 'about page' with the 'ü'
(see image as example)
![Capture](https://user-images.githubusercontent.com/26116060/76468520-6a980200-63ec-11ea-9363-b85f2557e110.PNG)

**Comment by HybridFox** [comment]
Picking up this evening :)

**Comment by HybridFox** [comment]
@inekdebo where can i find the logo for the navbar? It isnt available in the linked folder. I have updated the favicon in Fluufff/website@9b5636ce,

edit: nevermind about the logo, google drive was being weird

**Comment by HybridFox** [comment]
All updated in multiple commits
