### ISSUE TITLE
SUGGESTION: Don't allow 'assign to me' when you already assigned one room and one sponsor pack to yourself

### ISSUE THREAD

**Issue by HypiTheFox** [Fluufff/Website-issues#26]

**Comment by gabrielTach** [comment]
If I recall it correctly, this has already been discussed and will need an extra number of checks. It is not hard to implement but is it worth it?
I haven't had any request from the registration team. There has also been the case of people buying two spots for themself on purpose, it is less often than someone assigning by mistake two times the same spot to himself but is it still worth the time coding?

As long as there isn't a request for such a feature I will not add it to the TODO list.
