### ISSUE TITLE
[Bug] Cannot choose language from Burger Menu

### ISSUE THREAD

**Issue by gabrielTach** [Fluufff/Website-issues#33]
**How to reproduce**
1. Click on the burger menu.
2. Click on the current language.

**Description**
No choices got suggested.
The browser console does not output Javascript errors. 

**Problem**
There should be a selection of languages.

**Notes **
- Ubuntu 21.10 / Firefox 99.0.

**Comment by HybridFox** [comment]
Fixed on test

**Comment by gabrielTach** [comment]
:+1:
