### ISSUE TITLE
[Bug] Language switching on the website does not change the language in Platy+

### ISSUE THREAD

**Issue by gabrielTach** [Fluufff/Website-issues#34]
**How to reproduce**
1. Switch the language on the homepage
2. Go to the login/profile page in Platy+

**Description**
The language isn't changed for Platy+.

**Problem**
What is the actual issue (if it is not 100% obvious from the description above).

**Notes**
- Ubuntu 21.10 / Firefox 99.0..
- Use the same key as Platy+ (_lang_ instead of _activateLanguage_).

**Comment by HybridFox** [comment]
God, I tried sorting this, but something kept overwriting the key for some reason. I will try to look at it this evening 🙈

**Comment by HybridFox** [comment]
Ok seems PHP is still interferring with the lang when changing the cookie

**Comment by HybridFox** [comment]
Fixed on test

**Comment by gabrielTach** [comment]
It works, however when I try to switch from Dutch to English or French, nothing happens

**Comment by HybridFox** [comment]
Oh ye i see, double query params. I will fix!

**Comment by HybridFox** [comment]
_Actually_ fixed now

**Comment by gabrielTach** [comment]
It's near perfect! I can select the language now, but I can't see which one was the selected one in the burger menu.

**Comment by HybridFox** [comment]
Added ^^

**Comment by gabrielTach** [comment]
:+1:
