### ISSUE TITLE
[Bug] Incorrect URL for staff's avatars

### ISSUE THREAD

**Issue by gabrielTach** [Fluufff/Website-issues#36]
**How to reproduce**
1. Go to 'About'
2. Scroll down to 'Dreamteam'

**Description**
The avatars are not displayed.

**Problem**
The wrong URL is called: http://platyplus.test instead of the current website URL.

**Notes **
Suggestion: do not hard encode the website URL `url(http://platyplus.test/${attendee.avatar.original})`.

**Comment by HybridFox** [comment]
Fixed on test :)

**Comment by gabrielTach** [comment]
:+1:
