### ISSUE TITLE
[BUG] Rooms lists leads to a 404

### ISSUE THREAD

**Issue by SilouFr** [Fluufff/Website-issues#38]
**How to reproduce**
1. Go to 'administration page'
2. Click on 'booking'
3. Scroll down to 'rooms lists'

**Description**
I clicked on "rooms lists", also known as /admin/rooms/rooms-list
This leads now to a 404

**Problem**
404 ERROR

**Notes **
Was working on previous version, I created rooms on
The room creation pages is accessible

**Comment by gabrielTach** [comment]
Fixed, thanks for reporting! :)
