### ISSUE TITLE
[Bug] Links to con rules not working

### ISSUE THREAD

**Issue by Ziiari** [Fluufff/Website-issues#45]
**How to reproduce**
1. Go to the "About" Page
3. Click on the link to the con rules
4. You get right back to the beginning of the "About" Page

**Description**
The link on the "About" Page for the con rules doesn't work properly

**Problem**
The link just reloads the "About" page and you don't get to the con rules page

**Notes **
- Browser/OS/etc: Opera GX, Windows 10
- Suggestion: Fixing the link to go to the actual rules instead of just reloading the page maybe?

**Comment by gabrielTach** [comment]
Fixed
