### ISSUE TITLE
[Bug] Adapted bedroom selection is enabled by default

### ISSUE THREAD

**Issue by Akylian58** [Fluufff/Website-issues#46]
**How to reproduce**
![image](https://user-images.githubusercontent.com/74461755/168418214-165ac86d-537d-4d9a-a0f3-8934d0a455e7.png)

**Description**
The "adapted bedroom" flag is set to enabled for all people who have an account already. I had to turn it off myself.

**Problem**
We can't give everyone an adapted room for disabled people

**Notes **
Since these accounts were created by the admin I can't be sure this is a general issue, but I doubt he would have selected this himself each time.

**Comment by gabrielTach** [comment]
Fixed. Not a bug, it's a missconfiguration.
