### ISSUE TITLE
[Feature] Total Sum at Payment info

### ISSUE THREAD

**Issue by AzanaMau** [Fluufff/Website-issues#47]
Currently it says: 

Here are the payment instructions.

IBAN: BE96 9731 6607 0805
BIC: ARSPBE22
Name: Flüüfff
Address: Flüüfff ASBL – Rue Félicien Rops, 35B, boîte 01 – 1070, Anderlecht – BELGIQUE
Communication (in French banks: Commentaire/Libellé/Référence Opération): FLUUFFF2020A24

Maybe change it to:

Here are the payment instructions.

**Total Sum: xxxxxx**
**Payment Deadline: DD/MM/YYYY**
IBAN: BE96 9731 6607 0805
BIC: ARSPBE22
Name: Flüüfff
Address: Flüüfff ASBL – Rue Félicien Rops, 35B, boîte 01 – 1070, Anderlecht – BELGIQUE
Communication (in French banks: Commentaire/Libellé/Référence Opération): FLUUFFF2020A24

Just an idea <3 Thaaaaaanks

**Comment by gabrielTach** [comment]
Fixed, will be available in a next version
