### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by inekdebo** [Fluufff/Website-issues#5]
Homepage:

- everybodies -> everybody's

About: 

- On the homepage you use "4th", on the about page you use "fourth". I would go with 4th on each page.
- revenues -> revenue
- Belgique -> Belgium

Venue:
- stone-throw -> stone's throw

Activities:
- everybodies -> everybody's
-  The access -> Access
- zepto -> Zepto (capitalized)
- "He's a jolly fellow who helpers both artists.." -> He's a jolly fellow who **helps** both artists..
- "The bar, a good place to socialise with other DIY ethusiasts, a drink in hand." -> Is this text still relevant?
- "Grotta" -> Gotta

**Comment by gabrielTach** [comment]
Partially solved in Fluufff/website@dfa16e774.
Waiting for new texts in the Activities page.

**Comment by gabrielTach** [comment]
Activities fixed Fluufff/Website@2e1e8e0aeb3590c88f5cf03f61d651a8a2ecab2c.
