### ISSUE TITLE
[Bug] Bank transfer comment still refers to 2020

### ISSUE THREAD

**Issue by Akylian58** [Fluufff/Website-issues#53]
**How to reproduce**
https://fluufff.org/admin/registration/payment-method/banktransfer

Text still refers to 2020

**Description**
We are living in the past. The future is now old man!

**Problem**
People get confused.

**Notes **
![image](https://user-images.githubusercontent.com/74461755/168465148-5110cefb-d9c4-437d-be47-2921029734d9.png)

**Comment by gabrielTach** [comment]
Why are you taking a picture of your screen instead of a screenshot? :fearful:
