### ISSUE TITLE
[Feature] Add a Staff flag on the profiles

### ISSUE THREAD

**Issue by Akylian58** [Fluufff/Website-issues#54]
**Is your feature request related to a problem? Please describe.**
I could have sworn this was the case before, but I can't check if someone is staff from their profile in the Admin panel

**Describe the solution you'd like**
Have a flag that is hidden for the user, but visible for the administrators, maybe enable it by default when regging via the custom URL.

**Describe alternatives you've considered**
Remembering names is difficult.

**Additional context**
I am an old bird and I don't know everyone. I need somewhere to check whether someone is staff or not in the system.
Maybe have it listed here with the other info:

**Comment by gabrielTach** [comment]
Please avoid uploading personal information. (removed screenshot)

**Comment by gabrielTach** [comment]
1. Create a "Volunteer" ticket.
2. Ask your HR team to provide you the list of volunteers.
3. Assign a Volunteer ticket to the volunteers.
4. Ask the admin to configure Platy+ to have the staff logo on the attendees list.
