### ISSUE TITLE
[Bug] Stocks for triple rooms are -1

### ISSUE THREAD

**Issue by Akylian58** [Fluufff/Website-issues#55]
**How to reproduce**

https://test.fluufff.org/admin/products/stocks

![image](https://user-images.githubusercontent.com/74461755/168478138-0fd9dc8a-5e3c-4888-9d57-5737785c2e13.png)

**Description**
Stocks are set to -1 while they should be 24/12/12/12

**Problem**
I get stressed out about this.

**Notes **
I have no notes

**Comment by gabrielTach** [comment]
- There were 9 spots available to the attendees
- All of the 9 spots are used, plus 1 that got assigned manually by an admin. (9 - 10 = - 1)
