### ISSUE TITLE
[Feature] Show an attendee the amount left to pay when selecting bank transfer

### ISSUE THREAD

**Issue by Akylian58** [Fluufff/Website-issues#58]
**Is your feature request related to a problem? Please describe.**
When selecting bank transfer, when on the page with the payment instructions, there is no indication of the amount left to pay.
People thus have to write down or memorize the number, before they can get to the page with the IBAN, comment info etc.

**Describe the solution you'd like**
https://test.fluufff.org/admin/registration/payment-method/banktransfer contains a variable field based on the amount of money left to pay.

**Describe alternatives you've considered**
Teaching people how to write with pen and paper.

**Additional context**
![image](https://user-images.githubusercontent.com/74461755/169352406-0308413e-1151-43e7-b551-bdd872d75b90.png)

**Comment by gabrielTach** [comment]
Coming with the next update, however the "Amount" line has been on top, not on the bottom as in your example.
