### ISSUE TITLE
[Bug] No emojis on tickets

### ISSUE THREAD

**Issue by Akylian58** [Fluufff/Website-issues#59]
**How to reproduce**
Check the tickets.
https://test.fluufff.org/register/step/4/

**Description**
The emoji's created in the admin panel don't show up for the user.

**Problem**
????/????

**Notes**
-Firefox

![image](https://user-images.githubusercontent.com/74461755/169353901-da00134d-a239-40eb-b010-1fc25a6c5591.png)

**Comment by gabrielTach** [comment]
Will be fix in a next version, due to MySQL Database's encoding
