### ISSUE TITLE
Remove gradient and border from IFrames

### ISSUE THREAD

**Issue by inekdebo** [Fluufff/Website-issues#6]
Remove them from the iframes on the Tickets and Contact page (and others that i might have missedN). They cause unnecessary inconsistencies. Background color should be the standard pallette red (#a01922).

**Comment by HybridFox** [comment]
Are we talking about the background in platy+ then? Is this something we want to change right now @gabrielTach ?

**Comment by gabrielTach** [comment]
Yes it is. You can try.

**Comment by HybridFox** [comment]
Updated in https://github.com/Fluufff/Website/commit/79b95cb0567f95e9b3b69cd6c26144ac106f09fb

**Comment by inekdebo** [comment]
Seems like the contact page has still a gradient and border around the IFrames.
Background color should be the standard pallette red (#a01922).

Also thank you for fixing already the background in platy+!

**Comment by gabrielTach** [comment]
Fixed
