### ISSUE TITLE
[Feature] Clamp amount of rooms still available

### ISSUE THREAD

**Issue by HybridFox** [Fluufff/Website-issues#61]
Clamp between 0 and ... to prevent this scenario
![image](https://user-images.githubusercontent.com/7349146/169647957-c15512f7-7bf4-4759-8f17-ab2fecb2522b.png)

**Comment by gabrielTach** [comment]
Ah! I thought I did fix it in the past, apparently I didn't.
Fixed in 0a732fb16a6a791f8f6afec12be5ebc8f1519adc
