### ISSUE TITLE
[Bug] info for bank transfer 

### ISSUE THREAD

**Issue by fenax** [Fluufff/Website-issues#64]
Nowhere can I find the info to make a wire transfer.
The account number and amount I can find on the invoice but the communication is nowhere.

**Comment by gabrielTach** [comment]
Not a bug.

You can find it again when you click on "Pay"  next to the invoice on your profile, and then choose "Bank Transfer" again.

**Comment by fenax** [comment]
I think I know why.
On mobile it is out of the screen, with no way of knowing that there is more data in the array.

![_20220526_090635](https://user-images.githubusercontent.com/505783/170436301-d78ff5bf-1b49-4037-bcc5-47b3f6de0376.JPG)
