### ISSUE TITLE
A few hidden links

### ISSUE THREAD

**Issue by JewelTheIllumi** [Fluufff/Website-issues#8]
I have found a few hidden links at places where there isn't a button. 
Here's an overview:

**/activities**
-Hidden link at the show night tekst. when hovering over it, you'll see that it's clickable. the page redirects back to activites.

**/home**
-Homepage. the activity texts also have a hidden link. the text of dances, panels and show night are clickable, and redirect you to the homepage of fluufff.
the discover buttons work as they should, though.

**Comment by gabrielTach** [comment]
Thank you!

Fixed in Fluufff/Website-issues@3da73f40fa45bd5560ae9dae61eb89f58acbd705 .
